services:
  postgres:
    image: postgres:18
    container_name: n8n-postgres
    restart: unless-stopped
    env_file: .env
    environment:
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8 --lc-collate=en_US.UTF-8 --lc-ctype=en_US.UTF-8"
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U n8n_user -d n8n"]
      interval: 10s
      timeout: 5s
      retries: 5

  mongodb:
    image: mongo:7.0
    container_name: mongodb
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME:-admin}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD:-mG9vK2qP7wR4zT9yL5hN8bM3}
      MONGO_INITDB_DATABASE: n8n_chat_db
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
      - ./mongo-init:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:8.2.2-alpine
    container_name: redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    command: redis-server --appendonly yes

  n8n:
    image: docker.n8n.io/n8nio/n8n
    container_name: n8n
    restart: unless-stopped
    ports:
      - "5678:5678"
    env_file: .env
    environment:
      - DB_POSTGRESDB_HOST=postgres
      - DB_POSTGRESDB_PORT=5432
    volumes:
      - n8n_data:/home/node/.n8n
    depends_on:
      postgres:
        condition: service_healthy

  fastapi:
    build: .
    container_name: backend
    restart: unless-stopped
    ports:
      - "8000:8000"
    volumes:
      - ./backend/images:/app/images
    env_file: .env
    environment:
      - TZ=UTC
      - MONGODB_URL=${MONGODB_URL:-mongodb://n8n_chat_app:chatAppPass123@mongodb:27017/n8n_chat_db?authSource=admin}
      - N8N_CHAT_WEBHOOK_URL=${N8N_CHAT_WEBHOOK_URL:-http://n8n:5678/webhook/chat}
      - N8N_OCR_WEBHOOK_URL=${N8N_OCR_WEBHOOK_URL:-http://n8n:5678/webhook/scan-question}
      - N8N_BASIC_AUTH_USER=${N8N_BASIC_AUTH_USER:-electrolytes_admin}
      - N8N_BASIC_AUTH_PASSWORD=${N8N_BASIC_AUTH_PASSWORD}
    depends_on:
      mongodb:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

volumes:
    postgres_data:
      driver: local
    n8n_data:
      driver: local
    mongodb_data:
      driver: local
    redis_data:
      driver: local